/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './password';
import * as i2 from '@angular/common';
export const PasswordModuleNgFactory:i0.NgModuleFactory<i1.PasswordModule> = i0.ɵcmf(i1.PasswordModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.NgLocalization,i2.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(512,i2.CommonModule,
          i2.CommonModule,([] as any[])),i0.ɵmpd(512,i1.PasswordModule,i1.PasswordModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BzaGFoL3Byb2plY3RzL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL3Bhc3N3b3JkL3Bhc3N3b3JkLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3BzaGFoL3Byb2plY3RzL3ByaW1lbmcvc3JjL2FwcC9jb21wb25lbnRzL3Bhc3N3b3JkL3Bhc3N3b3JkLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
